# Decision Tree Classifier

In this notebook, you will implement your own decision tree algorithm for the classification problem. You are supposed to learn:

* How to prepare the dataset for training and testing of the model (i.e. decision tree).
* How to implement the decision tree learning algorithm.
* How to classify unseen samples using your model (i.e. trained decision tree).
* How to evaluate the performance of your model.

**Instructions:**

* Read carefuly through this notebook. Be sure you understand what is provided to you, and what is required from you.
* Place your code/edit only in sections annotated with `### START CODE HERE ###` and `### END CODE HERE ###`.
* Use comments whenever the code is not self-explanatory.
* Submit an executable notebook (`*.ipynb`) with your solution to BlackBoard.

Enjoy :-)

## Packages

Following packages is all you need. Do not import any additional packages!

* [Pandas](https://pandas.pydata.org/) is a library providing easy-to-use data structures and data analysis tools.
* [Numpy](http://www.numpy.org/) library provides support for large multi-dimensional arrays and matrices, along with functions to operate on these.

In [1]:
import pandas as pd
import numpy as np

## Problem

You are given a dataset `mushrooms.csv` with characteristics/attributes of mushrooms, and your task is to implement, train and evaluate a decision tree classifier able to say whether a mushroom is poisonous or edible based on its attributes.

## Dataset

The dataset of mushroom characteristics is freely available at [Kaggle Datasets](https://www.kaggle.com/uciml/mushroom-classification) where you can find further information about the dataset. It consists of 8124 mushrooms characterized by 23 attributes (including the class). Following is the overview of attributes and values:

* class: edible=e, poisonous=p
* cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
* cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
* cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r,pink=p,purple=u,red=e,white=w,yellow=y
* bruises: bruises=t,no=f
* odor: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s
* gill-attachment: attached=a,descending=d,free=f,notched=n
* gill-spacing: close=c,crowded=w,distant=d
* gill-size: broad=b,narrow=n
* gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y
* stalk-shape: enlarging=e,tapering=t
* stalk-root: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r,missing=?
* stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
* stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
* stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y
* stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y
* veil-type: partial=p,universal=u
* veil-color: brown=n,orange=o,white=w,yellow=y
* ring-number: none=n,one=o,two=t
* ring-type: cobwebby=c,evanescent=e,flaring=f,large=l,none=n,pendant=p,sheathing=s,zone=z
* spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r,orange=o,purple=u,white=w,yellow=y
* population: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y
* habitat: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d

Let's load the dataset into so called Pandas dataframe.

In [2]:
mushrooms_df = pd.read_csv('mushrooms.csv')

Now we can take a closer look at the data.

In [3]:
mushrooms_df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
5        e         x           y         y       t    a               f   
6        e         b           s         w       t    a               f   
7        e         b           y         w       t    l               f   
8        p         x           y         w       t    p               f   
9        e         b           s         y       t    a               f   
10       e         x           y         y       t    l               f   
11       e         x           y         y       t    a               f   
12       e         b           s         y       t    a               f   
13       p         x           y         w       t    p               f   
14       e         x           f         n       f    n               f   
15       e         s           f         g       f    n               f   
16       e         f           f         w       f    n               f   
17       p         x           s         n       t    p               f   
18       p         x           y         w       t    p               f   
19       p         x           s         n       t    p               f   
20       e         b           s         y       t    a               f   
21       p         x           y         n       t    p               f   
22       e         b           y         y       t    l               f   
23       e         b           y         w       t    a               f   
24       e         b           s         w       t    l               f   
25       p         f           s         w       t    p               f   
26       e         x           y         y       t    a               f   
27       e         x           y         w       t    l               f   
28       e         f           f         n       f    n               f   
29       e         x           s         y       t    a               f   
...    ...       ...         ...       ...     ...  ...             ...   
8094     e         b           s         g       f    n               f   
8095     p         x           y         c       f    m               f   
8096     e         k           f         w       f    n               f   
8097     p         k           y         n       f    s               f   
8098     p         k           s         e       f    y               f   
8099     e         k           f         w       f    n               f   
8100     e         f           s         n       f    n               a   
8101     p         k           s         e       f    s               f   
8102     e         x           s         n       f    n               a   
8103     e         k           s         n       f    n               a   
8104     e         k           s         n       f    n               a   
8105     e         k           s         n       f    n               a   
8106     e         k           s         n       f    n               a   
8107     e         x           s         n       f    n               a   
8108     p         k           y         e       f    y               f   
8109     e         b           s         w       f    n               f   
8110     e         x           s         n       f    n               a   
8111     e         k           s         w       f    n               f   
8112     e         k           s         n       f    n               a   
8113     p         k           y         e       f    y               f   
8114     p         f           y         c       f    m               a   
8115     e         x          

You can also print an overview of all attributes with the counts of unique values.

In [4]:
mushrooms_df.describe().T

count unique top  freq
class                     8124      2   e  4208
cap-shape                 8124      6   x  3656
cap-surface               8124      4   y  3244
cap-color                 8124     10   n  2284
bruises                   8124      2   f  4748
odor                      8124      9   n  3528
gill-attachment           8124      2   f  7914
gill-spacing              8124      2   c  6812
gill-size                 8124      2   b  5612
gill-color                8124     12   b  1728
stalk-shape               8124      2   t  4608
stalk-root                8124      5   b  3776
stalk-surface-above-ring  8124      4   s  5176
stalk-surface-below-ring  8124      4   s  4936
stalk-color-above-ring    8124      9   w  4464
stalk-color-below-ring    8124      9   w  4384
veil-type                 8124      1   p  8124
veil-color                8124      4   w  7924
ring-number               8124      3   o  7488
ring-type                 8124      5   p  3968
spore-print-color         8124      9   w  2388
population                8124      6   v  4040
habitat                   8124      7   d  3148

The dataset is pretty much balanced. That's a good news for the evaluation.

## Dataset Preprocessing

As our dataset consist of nominal/categorical values only, we will encode the strings into integers which again should simplify our implementation.

In [5]:
def encode_labels(df):
    import sklearn.preprocessing
    encoder = {}
    for col in df.columns:
        le = sklearn.preprocessing.LabelEncoder()
        le.fit(df[col])
        df[col] = le.transform(df[col])
        encoder[col] = le
    return df, encoder    

mushrooms_encoded_df, encoder = encode_labels(mushrooms_df)

In [70]:
mushrooms_encoded_df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

## Dataset Splitting

Before we start with the implementation of our decision tree algorithm we need to prepare our dataset for the training and testing.

First, we divide the dataset into attributes (often called features) and classes (often called targets). Keeping attributes and classes separately is a common practice in many implementations. This should simplify the implementation and make the code understandable.

In [7]:
X_df = mushrooms_encoded_df.drop('class', axis=1)  # attributes
y_df = mushrooms_encoded_df['class']  # classes
X_array = X_df.as_matrix()
y_array = y_df.as_matrix()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


And this is how it looks like.

In [26]:
print('X =', X_array)
print('y =', y_array)

X = <class 'numpy.ndarray'>
y = [1 0 0 ... 0 1 0]


Next, we need to split the attributes and classes into training sets and test sets.

**Exercise:**

Implement the holdout splitting method with shuffling.

In [30]:
from random import seed
from random import randrange

def train_test_split(X, y, test_size=0.2):
    """
    Shuffles the dataset and splits it into training and test sets.
    
    :param X
        attributes
    :param y
        classes
    :param test_size
        float between 0.0 and 1.0 representing the proportion of the dataset to include in the test split
    :return
        train-test splits (X-train, X-test, y-train, y-test)
    """
    ### START CODE HERE ###
    # Shuffle first
    c = list(zip(X, y))
    test = list()
    test_size = test_size * len(c)
    copy = list(c)
    while len(test) < test_size:
        index = randrange(len(copy))
        test.append(copy.pop(index))
    X_train, y_train = zip(*copy)
    X_test, y_test =  zip(*test)
    
    
    ### END CODE HERE ###
    return np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)

Let's split the dataset into training and validation/test set with 67:33 split.

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, 0.33)

In [32]:
print('X_train =', X_train)
print('y_train =', y_train)
print('X_test =', X_test)
print('y_test =', y_test)

X_train = [[5 2 4 ... 2 3 5]
 [5 2 9 ... 3 2 1]
 [5 3 8 ... 2 3 5]
 ...
 [3 2 2 ... 7 4 0]
 [5 2 4 ... 0 4 2]
 [3 3 4 ... 7 4 2]]
y_train = [1 0 1 ... 1 0 1]
X_test = [[2 3 9 ... 1 4 0]
 [5 0 3 ... 3 5 0]
 [2 2 0 ... 1 4 1]
 ...
 [5 2 4 ... 7 4 4]
 [3 2 3 ... 7 2 1]
 [5 3 8 ... 2 3 1]]
y_test = [1 0 1 ... 1 0 0]


A quick sanity check...

In [33]:
assert len(X_train) == len(y_train)
assert len(y_train) == 5443
assert len(X_test) == len(y_test)
assert len(y_test) == 2681

## Training

**Exercise:**

Implement an algorithm for fitting (also called training or inducing) a decision tree.

* You have a free hand regarding the generation of candidate splits (also called attribute test conditions).
* Measure the degree of impurity (Gini) to select the best split.

In [127]:
# Use this section to place any "helper" code for the `fit()` function.

### START CODE HERE ###

def class_counts(y,col=None):
    """
    A function for counting the occurrence of the different labels in y
    (or attributes if col used)
    y: numpy.array[]
    """
    counts = {}
    for label in y:
        if col:
            label = label[col]
        if label not in counts:
            counts[label] = 0
        counts[label] += 1
    return counts

def gini(y):
    res = 1
    tot = len(y)
    counts = class_counts(y)
    for key in counts:
        res -= (counts[key]/tot)**2
    return res

# So Gini gives us the uncertanti of our training data
# We also neeed a function to tell us the information gain we 
# get by doing a certain partitioning
def info_gain(y_left, y_right, gini_value):
    p = float(len(y_left) / (len(y_left) + len(y_right)))
    return gini_value - p * gini(y_left) - (1-p)*gini(y_right)

# We could need a method to find the unique values of a column in a df
def unique_values(X, col):
    """
    df: numpy.array containing all the rows
    col: int telling the index of the row
    """
    return set((row[col] for row in X))

def stop_cond(X, y):
    """
    Function is used to terminate the tree-growing process
    by testing whether all the records have either the same class label
    or the same attribute values
    """
    # TODO: Check attributes as well
    class_count = class_counts(y)
    equal_class = min(class_count, key=class_count.get) == 0
    return equal_class

def partition(X, y, attribute, val):
    """
    Only return y_s
    """
    true_rows, false_rows = [],[]
    for x in range(len(X)):
        if X[x][attribute] == val:
            true_rows.append(y[x])
        else:
            false_rows.append(y[x])
    
    return true_rows, false_rows

def part(X, y, attribute, val):
    c = list(zip(X, y))
    c = list(filter(lambda x: x[0][attribute] == val, c))
    X_new, y_new = zip(*c)
    return np.array(X_new), np.array(y_new)

def find_best_split(X, y):
    """
    Find the best question to ask by iterating over every feature / value
    and calculating the information gain.
    """
    best_gain = 0
    best_attribute = None # keeps track of the best column
    best_value = None # keeps track of the feature / value that produced it

    current_uncertainty = gini(y)
    n_features = len(X[0]) # number of columns

    print("Finding best split...")
    for attribute in range(0, n_features): # for each feature
        values = unique_values(X, attribute) # unique values in the column

        for val in values: # for each of the unique values

            #question = Question(attribute, val)

            # Try splitting the dataset
            true_rows, false_rows = partition(X, y, attribute, val)

            # Skip if it does not divide the dataset
            if len(true_rows) == 0 or len(false_rows) == 0:
                continue

            # Calculate the information gain from this split
            gain = info_gain(true_rows, false_rows, current_uncertainty)

            # Update best results
            if gain >= best_gain:
                best_gain, best_attribute, best_value = gain, attribute, val
    print("Found best attribute: ", best_attribute, " and best value ", best_value)
    return best_attribute, best_value, best_gain


### END CODE HERE ###

In [128]:
# Objects

class Node():
    """
    A node in the decision tree has either a test condition, denoted as
    node.test-cond, or a class label, denoted as node.label.
    """
    
    def __init__(self):
        self.parent = None
        self.children = []
        
    def add_child(self, node):
        self.children.append(node)
    
    def set_parent(self, parent):
        self.parent = parent

In [129]:
def fit(X, y):
    """
    Function implementing decision tree induction.
    
    :param X
        attributes np.array
    :param y
        classes np.array
    :return
        trained decision tree (model)
    """
    ### START CODE HERE ### 

    root = Node()
    root.attribute, root.value, best_gain = find_best_split(X, y)

    if best_gain == 0:
        leaf = Node()
        class_count = class_counts(y)
        leaf.label = max(class_count, key=class_count.get) # Choose the label with highest occurence
        return leaf

    # Find all unique values of that attribute
    possible_outcomes = unique_values(X, root.attribute)

    for outcome in possible_outcomes:
        # Partition dataset for each possible outcome
        X_part, y_part = part(X, y, root.attribute, outcome)

        child = fit(X_part, y_part)
        root.add_child([child, outcome])
            
    ### END CODE HERE ### 
    return root

In [130]:
model = fit(X_train, y_train)

Finding best split...
Found best attribute:  4  and best value  5
Finding best split...
Found best attribute:  21  and best value  4
Finding best split...
Found best attribute:  20  and best value  4
Finding best split...
Found best attribute:  21  and best value  5
Finding best split...
Found best attribute:  21  and best value  4
Finding best split...
Found best attribute:  8  and best value  11
Finding best split...
Found best attribute:  19  and best value  5
Finding best split...
Found best attribute:  20  and best value  4
Finding best split...
Found best attribute:  20  and best value  5
Finding best split...
Found best attribute:  21  and best value  5
Finding best split...
Found best attribute:  21  and best value  5
Finding best split...
Found best attribute:  20  and best value  4
Finding best split...
Found best attribute:  21  and best value  3
Finding best split...
Found best attribute:  21  and best value  0
Finding best split...
Found best attribute:  20  and best value

## Prediction/Deduction

At this moment we should have trained a decision tree (our model). Now we need an algorithm for assigning a class given the attributes and our model.

**Exercise:**

Implement an algorithm deducing class given the attributes and the model.

* `X` is a matrix of attributes of one or more instances for classification.

In [ ]:
# Use this section to place any "helper" code for the `predict()` function.

### START CODE HERE ###

### END CODE HERE ###

In [ ]:
def predict(X, model):
    """
    Function for generating predictions (classifying) given attributes and model.
    
    :param X
        attributes
    :param model
        model
    :return
        predicted classes (y_hat)
    """
    ### START CODE HERE ###

    ### END CODE HERE ###
    return y_hat

Let's classify the instances of our test set.

In [ ]:
y_hat = predict(X_test, model)

First ten predictions of the test set.

In [ ]:
y_hat[:10]

## Evaluation

Now we would like to assess how well our decision tree classifier performs.

**Exercise:**

Implement a function for calculating the accuracy of your predictions given the ground truth and predictions.

In [ ]:
def evaluate(y_true, y_pred):
    """
    Function calculating the accuracy of the model given the ground truth and predictions.
    
    :param y_true
        true classes
    :param y_pred
        predicted classes
    :return
        accuracy
    """
    ### START CODE HERE ###

    ### END CODE HERE ### 
    return accuracy

In [ ]:
accuracy = evaluate(y_test, y_hat)
print('accuracy =', accuracy)

How many items where misclassified?

In [ ]:
print('misclassified =', sum(abs(y_hat - y_test)))

How balanced is our test set?

In [ ]:
np.bincount(y_test)

If it's balanced, we don't have to be worried about objectivity of the accuracy metric.

---

Congratulations! At this point, hopefully, you have successufuly implemented a decision tree algorithm able to classify unseen samples with high accuracy.

✌️